### ISSUE TITLE
Adding new Cryptocurrency app in finance section

### ISSUE THREAD

**Issue by pranayairan** [jiwonbest/amazing-android-apps#5]
Hi,

I recently created a beautiful cryptocurrency app Coiny. I wanted to check if It is possible for you to list my application in the finance section of this repo. 

This is my app's link: https://github.com/pranayairan/coiny

**Comment by codeteo** [comment]
Hi @pranayairan,

I'm getting a 404 Page Not Found error when I click the [link](https://github.com/pranayairan/coiny) for the Coiny app.
Maybe you changed the app to private? 

Thanks.

**Comment by pranayairan** [comment]
Yes currently it is not published, I will reopen the issue in the future. Thanks.
